### El metodo de K-means

In [1]:
import numpy as np 

In [4]:
data= np.random.random(90).reshape(30, 3)
data

array([[0.23805495, 0.22592222, 0.40262874],
       [0.84401007, 0.2165415 , 0.36027578],
       [0.3489907 , 0.81943942, 0.50700588],
       [0.55244164, 0.12213152, 0.2900342 ],
       [0.81213767, 0.4267304 , 0.07117115],
       [0.96303663, 0.95790439, 0.83810681],
       [0.06296718, 0.21763719, 0.27167112],
       [0.74404528, 0.89261396, 0.79869529],
       [0.37563446, 0.25949706, 0.76622589],
       [0.23966274, 0.0738697 , 0.36890605],
       [0.20354943, 0.56814558, 0.88687128],
       [0.58633886, 0.52346076, 0.69734462],
       [0.33976009, 0.50031575, 0.36175143],
       [0.98341674, 0.10825603, 0.02767154],
       [0.84000446, 0.14255392, 0.1629683 ],
       [0.92223572, 0.569095  , 0.57320507],
       [0.28312484, 0.28690971, 0.72885919],
       [0.8632478 , 0.45520899, 0.78512844],
       [0.05003107, 0.69419518, 0.97268079],
       [0.1371241 , 0.34792083, 0.7926964 ],
       [0.34925292, 0.48848119, 0.83734136],
       [0.66378801, 0.94967272, 0.81997905],
       [0.

In [7]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers= np.vstack([data[c1], data[c2]])

In [8]:
from scipy.cluster.vq import vq

In [9]:
vq(data, clust_centers)

(array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1]),
 array([0.69264639, 0.35885472, 0.46261243, 0.45620559, 0.        ,
        0.29991017, 0.80322887, 0.10074686, 0.74984285, 0.73544836,
        0.60154558, 0.45021574, 0.55945713, 0.36421788, 0.29993257,
        0.52204599, 0.76971558, 0.53431559, 0.68211742, 0.80014033,
        0.55850819, 0.        , 0.716803  , 0.61981858, 0.5910462 ,
        0.49396725, 0.56391164, 0.21801866, 0.50503772, 0.49374027]))

In [10]:
from scipy.cluster.vq import kmeans